/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/device/bindDevice" |
       "/pages/device/deviceConnect" |
       "/pages/device/deviceHub" |
       "/pages/device/devicePermissions" |
       "/pages/device/searchDevice" |
       "/pages/user/albumCenter" |
       "/pages/user/complaintCenter" |
       "/pages/user/guideCenter" |
       "/pages/user/miniLocation" |
       "/pages/user/people" |
       "/pages/user/profileInfo" |
       "/pages/user/settingsCenter" |
       "/pages/user/themeCenter";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/device/deviceHub" | "/pages/user/people"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
